apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      name: flask-app
      labels:
        app: flask-app
    spec: 
      containers:
        - image: soaresalex/repoflask:1.0.0
          name: container-flask
          ports: 
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources: {}