apiVersion: v1 #Versão da API
kind: Pod #Tipo do objeto
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  containers:
    - name: container-flask
      image: soaresalex/repoflask:1.0.0
      ports:
        - containerPort: 5000

      
